/**
 * ==========================================
 * REAL LISTINGS DATABASE
 * ==========================================
 * 
 * 30 realistic property listings across major Indian cities.
 * Used by both the API server and frontend static fallback.
 * Inspired by 99acres, MagicBricks, Housing.com
 */

const REAL_LISTINGS = [
    {
        id: 'prop_001',
        title: 'Luxurious 3 BHK in Gomti Nagar Extension',
        description: 'Step into luxury living with this beautifully crafted 3 BHK apartment featuring Italian marble flooring, modular kitchen with chimney, and panoramic balcony views. Located in the heart of Gomti Nagar Extension with easy access to Phoenix Palassio Mall and Lucknow Metro.',
        propertyType: 'flat',
        listingType: 'sell',
        bhk: '3 BHK',
        bathrooms: 2,
        sqft: 1450,
        furnishing: 'semi-furnished',
        price: 8500000,
        latitude: 26.8467,
        longitude: 80.9462,
        address: 'Sector 12, Gomti Nagar Extension, Lucknow',
        city: 'Lucknow',
        area: 'Gomti Nagar',
        pincode: '226010',
        amenities: ['Parking', 'Lift', '24x7 Security', 'Park', 'Gym', 'Children Play Area', 'Power Backup', 'CCTV'],
        images: [
            'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop'
        ],
        yearBuilt: 2022,
        verificationStatus: 'verified',
        isFeatured: true,
        status: 'active',
        owner: { id: 'user_001', name: 'Rajesh Kumar Verma', phone: '+919876543210', email: 'rajesh.verma@gmail.com', isVerified: true },
        viewCount: 342, contactCount: 28,
        createdAt: new Date('2026-01-15').toISOString()
    },
    {
        id: 'prop_002',
        title: 'Affordable 2 BHK Near Alambagh Bus Station',
        description: 'Well-designed 2 BHK apartment just 5 minutes from Alambagh Bus Station. Perfect for working professionals and small families. Features cross-ventilation, spacious rooms, and dedicated parking.',
        propertyType: 'flat',
        listingType: 'sell',
        bhk: '2 BHK',
        bathrooms: 2,
        sqft: 980,
        furnishing: 'unfurnished',
        price: 4500000,
        latitude: 26.8205,
        longitude: 80.8869,
        address: 'Kanpur Road, Alambagh, Lucknow',
        city: 'Lucknow',
        area: 'Alambagh',
        pincode: '226005',
        amenities: ['Parking', 'Lift', 'Security', 'Water Supply 24x7'],
        images: [
            'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop'
        ],
        yearBuilt: 2019,
        verificationStatus: 'verified',
        isFeatured: false,
        status: 'active',
        owner: { id: 'user_002', name: 'Priya Sharma', phone: '+919845612378', email: 'priya.sharma@gmail.com', isVerified: true },
        viewCount: 189, contactCount: 15,
        createdAt: new Date('2026-01-20').toISOString()
    },
    {
        id: 'prop_003',
        title: 'Premium 4 BHK Villa in Hazratganj',
        description: 'An exclusive 4 BHK villa in the prestigious Hazratganj area. Features private garden, home theater room, servants quarter, and Italian marble throughout. Walking distance to heritage markets and fine dining restaurants.',
        propertyType: 'villa',
        listingType: 'sell',
        bhk: '4 BHK',
        bathrooms: 4,
        sqft: 3200,
        furnishing: 'fully-furnished',
        price: 25000000,
        latitude: 26.8547,
        longitude: 80.9470,
        address: 'MG Marg, Hazratganj, Lucknow',
        city: 'Lucknow',
        area: 'Hazratganj',
        pincode: '226001',
        amenities: ['Parking', 'Swimming Pool', 'Garden', 'Security', 'Gym', 'Home Theater', 'Servants Quarter', 'Modular Kitchen'],
        images: [
            'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop'
        ],
        yearBuilt: 2023,
        verificationStatus: 'verified',
        isFeatured: true,
        status: 'active',
        owner: { id: 'user_001', name: 'Rajesh Kumar Verma', phone: '+919876543210', email: 'rajesh.verma@gmail.com', isVerified: true },
        viewCount: 567, contactCount: 42,
        createdAt: new Date('2026-01-10').toISOString()
    },
    {
        id: 'prop_004',
        title: '2 BHK Fully Furnished for Rent — Indira Nagar',
        description: 'Ready-to-move-in 2 BHK with premium furniture, AC in all rooms, modular kitchen with appliances, high-speed WiFi, and washing machine. Gated society with 24x7 security. Ideal for IT professionals.',
        propertyType: 'flat',
        listingType: 'rent',
        bhk: '2 BHK',
        bathrooms: 2,
        sqft: 1100,
        furnishing: 'fully-furnished',
        price: 22000,
        latitude: 26.8780,
        longitude: 80.9920,
        address: 'Sector 15, Indira Nagar, Lucknow',
        city: 'Lucknow',
        area: 'Indira Nagar',
        pincode: '226016',
        amenities: ['Parking', 'Lift', 'Security', 'Power Backup', 'AC', 'WiFi', 'Washing Machine', 'Modular Kitchen'],
        images: [
            'https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&h=600&fit=crop'
        ],
        yearBuilt: 2020,
        verificationStatus: 'verified',
        isFeatured: false,
        status: 'active',
        owner: { id: 'user_003', name: 'Sanjay Gupta', phone: '+919988776655', email: 'sanjay.gupta@gmail.com', isVerified: true },
        viewCount: 290, contactCount: 35,
        createdAt: new Date('2026-01-25').toISOString()
    },
    {
        id: 'prop_005',
        title: 'Modern 3 BHK with Club House — Mahanagar',
        description: 'Contemporary architecture 3 BHK flat with floor-to-ceiling windows, wooden flooring in master bedroom, and access to a world-class clubhouse with swimming pool, gym, and party hall.',
        propertyType: 'flat',
        listingType: 'sell',
        bhk: '3 BHK',
        bathrooms: 2,
        sqft: 1350,
        furnishing: 'semi-furnished',
        price: 7500000,
        latitude: 26.8850,
        longitude: 81.0050,
        address: 'Sector A, Mahanagar Extension, Lucknow',
        city: 'Lucknow',
        area: 'Mahanagar',
        pincode: '226006',
        amenities: ['Parking', 'Lift', 'Security', 'Park', 'Club House', 'Swimming Pool', 'Gym', 'Party Hall'],
        images: [
            'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop'
        ],
        yearBuilt: 2021,
        verificationStatus: 'verified',
        isFeatured: true,
        status: 'active',
        owner: { id: 'user_002', name: 'Priya Sharma', phone: '+919845612378', email: 'priya.sharma@gmail.com', isVerified: true },
        viewCount: 410, contactCount: 31,
        createdAt: new Date('2026-01-28').toISOString()
    },
    {
        id: 'prop_006',
        title: 'Cozy 1 BHK Studio in Aliganj',
        description: 'Perfect starter home — compact yet well-designed 1 BHK with open kitchen concept, ample natural light, and balcony. Located near Aliganj market and well connected by public transport.',
        propertyType: 'flat',
        listingType: 'sell',
        bhk: '1 BHK',
        bathrooms: 1,
        sqft: 650,
        furnishing: 'unfurnished',
        price: 3200000,
        latitude: 26.8900,
        longitude: 80.9150,
        address: 'Near Aliganj Crossing, Lucknow',
        city: 'Lucknow',
        area: 'Aliganj',
        pincode: '226024',
        amenities: ['Parking', 'Security', 'Water Supply 24x7'],
        images: [
            'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&h=600&fit=crop'
        ],
        yearBuilt: 2018,
        verificationStatus: 'verified',
        isFeatured: false,
        status: 'active',
        owner: { id: 'user_003', name: 'Sanjay Gupta', phone: '+919988776655', email: 'sanjay.gupta@gmail.com', isVerified: true },
        viewCount: 156, contactCount: 12,
        createdAt: new Date('2026-01-22').toISOString()
    },
    {
        id: 'prop_007',
        title: 'Ultra-Luxury 4 BHK Penthouse — Sushant Golf City',
        description: 'Sky-high living in this duplex penthouse with private terrace garden, panoramic golf course views, smart home automation, Italian kitchen, jacuzzi, and dedicated elevator access. The pinnacle of Lucknow luxury.',
        propertyType: 'flat',
        listingType: 'sell',
        bhk: '4 BHK',
        bathrooms: 4,
        sqft: 4000,
        furnishing: 'fully-furnished',
        price: 35000000,
        latitude: 26.7920,
        longitude: 81.0340,
        address: 'Sushant Golf City, Amar Shaheed Path, Lucknow',
        city: 'Lucknow',
        area: 'Sushant Golf City',
        pincode: '226030',
        amenities: ['Parking', 'Lift', 'Swimming Pool', 'Gym', 'Security', 'Golf Course View', 'Terrace Garden', 'Smart Home', 'Jacuzzi', 'EV Charging'],
        images: [
            'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop'
        ],
        yearBuilt: 2024,
        verificationStatus: 'verified',
        isFeatured: true,
        status: 'active',
        owner: { id: 'user_004', name: 'Amit Agarwal', phone: '+919876501234', email: 'amit.agarwal@gmail.com', isVerified: true },
        viewCount: 891, contactCount: 65,
        createdAt: new Date('2026-01-05').toISOString()
    },
    {
        id: 'prop_008',
        title: 'Independent 3 BHK House with Garden — Jankipuram',
        description: 'Spacious independent house with private lawn, car porch for 2 cars, terrace, and servant room. Perfect for families seeking privacy and space in a well-developed residential colony.',
        propertyType: 'house',
        listingType: 'sell',
        bhk: '3 BHK',
        bathrooms: 3,
        sqft: 2000,
        furnishing: 'semi-furnished',
        price: 12000000,
        latitude: 26.8650,
        longitude: 80.8850,
        address: 'Sector C, Jankipuram Extension, Lucknow',
        city: 'Lucknow',
        area: 'Jankipuram',
        pincode: '226021',
        amenities: ['Parking', 'Garden', 'Security', 'Terrace', 'Servant Room'],
        images: [
            'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop'
        ],
        yearBuilt: 2020,
        verificationStatus: 'verified',
        isFeatured: false,
        status: 'active',
        owner: { id: 'user_002', name: 'Priya Sharma', phone: '+919845612378', email: 'priya.sharma@gmail.com', isVerified: true },
        viewCount: 203, contactCount: 18,
        createdAt: new Date('2026-01-30').toISOString()
    },
    // ==================== NOIDA / DELHI NCR ====================
    {
        id: 'prop_009',
        title: 'Stunning 3 BHK in ATS Greens — Noida Sector 150',
        description: 'Premium apartment in ATS Greens with lush green views, Olympic-size swimming pool, and world-class sports facilities. Direct expressway connectivity to Delhi. Perfect for corporate professionals.',
        propertyType: 'flat',
        listingType: 'sell',
        bhk: '3 BHK',
        bathrooms: 3,
        sqft: 1800,
        furnishing: 'semi-furnished',
        price: 12500000,
        latitude: 28.5694,
        longitude: 77.3510,
        address: 'ATS Greens, Sector 150, Noida',
        city: 'Noida',
        area: 'Sector 150',
        pincode: '201310',
        amenities: ['Parking', 'Lift', 'Swimming Pool', 'Gym', 'Security', 'Club House', 'Tennis Court', 'Jogging Track'],
        images: [
            'https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&h=600&fit=crop'
        ],
        yearBuilt: 2023,
        verificationStatus: 'verified',
        isFeatured: true,
        status: 'active',
        owner: { id: 'user_005', name: 'Vikram Singh Chauhan', phone: '+919811234567', email: 'vikram.chauhan@gmail.com', isVerified: true },
        viewCount: 445, contactCount: 38,
        createdAt: new Date('2026-02-01').toISOString()
    },
    {
        id: 'prop_010',
        title: '2 BHK Studio Apartment for Rent — Noida Sector 62',
        description: 'Modern 2 BHK near IT hub of Sector 62. Walking distance to Noida Electronic City Metro Station. Fully furnished with AC, washing machine, and modular kitchen. Ideal for working couples.',
        propertyType: 'flat',
        listingType: 'rent',
        bhk: '2 BHK',
        bathrooms: 2,
        sqft: 1050,
        furnishing: 'fully-furnished',
        price: 25000,
        latitude: 28.6270,
        longitude: 77.3650,
        address: 'Near Electronic City Metro, Sector 62, Noida',
        city: 'Noida',
        area: 'Sector 62',
        pincode: '201309',
        amenities: ['Parking', 'Lift', 'Security', 'AC', 'WiFi', 'Power Backup', 'Gym'],
        images: [
            'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&h=600&fit=crop'
        ],
        yearBuilt: 2021,
        verificationStatus: 'verified',
        isFeatured: false,
        status: 'active',
        owner: { id: 'user_005', name: 'Vikram Singh Chauhan', phone: '+919811234567', email: 'vikram.chauhan@gmail.com', isVerified: true },
        viewCount: 312, contactCount: 41,
        createdAt: new Date('2026-02-03').toISOString()
    },
    {
        id: 'prop_011',
        title: '5 BHK Villa in DLF Phase 5 — Gurgaon',
        description: 'Sprawling 5 BHK villa in the elite DLF Phase 5, Gurgaon. Features private pool, landscaped garden, home office, wine cellar, and 3-car garage. Minutes from Cyber Hub and premium shopping destinations.',
        propertyType: 'villa',
        listingType: 'sell',
        bhk: '5 BHK',
        bathrooms: 5,
        sqft: 5500,
        furnishing: 'fully-furnished',
        price: 85000000,
        latitude: 28.4595,
        longitude: 77.0930,
        address: 'DLF Phase 5, Gurgaon, Haryana',
        city: 'Gurgaon',
        area: 'DLF Phase 5',
        pincode: '122009',
        amenities: ['Private Pool', 'Garden', 'Home Office', 'Wine Cellar', '3-Car Garage', 'Smart Home', 'Security', 'Servant Quarter', 'EV Charging'],
        images: [
            'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop'
        ],
        yearBuilt: 2024,
        verificationStatus: 'verified',
        isFeatured: true,
        status: 'active',
        owner: { id: 'user_006', name: 'Neeraj Malhotra', phone: '+919871009876', email: 'neeraj.malhotra@gmail.com', isVerified: true },
        viewCount: 1200, contactCount: 85,
        createdAt: new Date('2026-02-05').toISOString()
    },
    {
        id: 'prop_012',
        title: '3 BHK in Gaur City — Greater Noida West',
        description: 'Spacious 3 BHK in the popular Gaur City township with extensive green areas, mall, school, and hospital within the complex. Excellent investment opportunity with proposed metro connectivity.',
        propertyType: 'flat',
        listingType: 'sell',
        bhk: '3 BHK',
        bathrooms: 2,
        sqft: 1550,
        furnishing: 'unfurnished',
        price: 6800000,
        latitude: 28.5840,
        longitude: 77.4240,
        address: 'Gaur City 2, Greater Noida West',
        city: 'Greater Noida',
        area: 'Greater Noida West',
        pincode: '201318',
        amenities: ['Parking', 'Lift', 'Security', 'Park', 'Swimming Pool', 'Club House', 'School Nearby', 'Mall Nearby'],
        images: [
            'https://images.unsplash.com/photo-1567496898669-ee935f5f647a?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&h=600&fit=crop'
        ],
        yearBuilt: 2022,
        verificationStatus: 'verified',
        isFeatured: false,
        status: 'active',
        owner: { id: 'user_005', name: 'Vikram Singh Chauhan', phone: '+919811234567', email: 'vikram.chauhan@gmail.com', isVerified: true },
        viewCount: 198, contactCount: 14,
        createdAt: new Date('2026-02-07').toISOString()
    },
    // ==================== MUMBAI ====================
    {
        id: 'prop_013',
        title: 'Sea-View 2 BHK in Worli — Mumbai',
        description: 'Wake up to breathtaking Arabian Sea views in this 2 BHK apartment at Worli Seaface. High-rise tower with premium amenities, concierge service, and direct access to Bandra-Worli Sea Link. The Mumbai dream.',
        propertyType: 'flat',
        listingType: 'sell',
        bhk: '2 BHK',
        bathrooms: 2,
        sqft: 1200,
        furnishing: 'fully-furnished',
        price: 45000000,
        latitude: 19.0176,
        longitude: 72.8150,
        address: 'Worli Seaface, Mumbai',
        city: 'Mumbai',
        area: 'Worli',
        pincode: '400030',
        amenities: ['Sea View', 'Swimming Pool', 'Gym', 'Concierge', 'Parking', 'Lift', 'Security', 'Rooftop Lounge'],
        images: [
            'https://images.unsplash.com/photo-1600047509358-9dc75507daeb?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&h=600&fit=crop'
        ],
        yearBuilt: 2024,
        verificationStatus: 'verified',
        isFeatured: true,
        status: 'active',
        owner: { id: 'user_007', name: 'Arjun Mehra', phone: '+919821567890', email: 'arjun.mehra@gmail.com', isVerified: true },
        viewCount: 1560, contactCount: 92,
        createdAt: new Date('2026-02-09').toISOString()
    },
    {
        id: 'prop_014',
        title: '1 BHK in Andheri West for Rent',
        description: 'Well-maintained 1 BHK in a prime Andheri West location. 10 minutes walk to Andheri Metro and railway station. Close to Lokhandwala market, DN Nagar, and major IT offices. Perfect bachelor pad.',
        propertyType: 'flat',
        listingType: 'rent',
        bhk: '1 BHK',
        bathrooms: 1,
        sqft: 550,
        furnishing: 'semi-furnished',
        price: 35000,
        latitude: 19.1197,
        longitude: 72.8370,
        address: 'DN Nagar, Andheri West, Mumbai',
        city: 'Mumbai',
        area: 'Andheri West',
        pincode: '400053',
        amenities: ['Lift', 'Security', 'Water Supply 24x7', 'Power Backup'],
        images: [
            'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1585128792020-803d29415281?w=800&h=600&fit=crop'
        ],
        yearBuilt: 2017,
        verificationStatus: 'verified',
        isFeatured: false,
        status: 'active',
        owner: { id: 'user_008', name: 'Deepika Nair', phone: '+919833456789', email: 'deepika.nair@gmail.com', isVerified: true },
        viewCount: 678, contactCount: 89,
        createdAt: new Date('2026-02-10').toISOString()
    },
    {
        id: 'prop_015',
        title: '3 BHK in Powai Lake View — Hiranandani',
        description: 'Elegant 3 BHK in the iconic Hiranandani Gardens, Powai with stunning lake views. Features wooden flooring, European fittings, and access to gardens, gym, pool, and amphitheater. A self-sufficient township.',
        propertyType: 'flat',
        listingType: 'sell',
        bhk: '3 BHK',
        bathrooms: 3,
        sqft: 1650,
        furnishing: 'semi-furnished',
        price: 38000000,
        latitude: 19.1176,
        longitude: 72.9060,
        address: 'Hiranandani Gardens, Powai, Mumbai',
        city: 'Mumbai',
        area: 'Powai',
        pincode: '400076',
        amenities: ['Lake View', 'Swimming Pool', 'Gym', 'Garden', 'Parking', 'Lift', 'Security', 'Amphitheater', 'Jogging Track'],
        images: [
            'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&h=600&fit=crop'
        ],
        yearBuilt: 2021,
        verificationStatus: 'verified',
        isFeatured: true,
        status: 'active',
        owner: { id: 'user_007', name: 'Arjun Mehra', phone: '+919821567890', email: 'arjun.mehra@gmail.com', isVerified: true },
        viewCount: 890, contactCount: 56,
        createdAt: new Date('2026-02-11').toISOString()
    },
    // ==================== BANGALORE ====================
    {
        id: 'prop_016',
        title: '3 BHK in Prestige Lakeside Habitat — Whitefield',
        description: 'Luxury living in Prestige Lakeside Habitat with 3 BHK overlooking a serene lake. World-class amenities including 9-hole golf course, Olympic pool, organic farm, and 80% open space. Tech corridor location.',
        propertyType: 'flat',
        listingType: 'sell',
        bhk: '3 BHK',
        bathrooms: 3,
        sqft: 1900,
        furnishing: 'semi-furnished',
        price: 18500000,
        latitude: 12.9698,
        longitude: 77.7500,
        address: 'Prestige Lakeside Habitat, Whitefield, Bangalore',
        city: 'Bangalore',
        area: 'Whitefield',
        pincode: '560066',
        amenities: ['Golf Course', 'Swimming Pool', 'Gym', 'Organic Farm', 'Club House', 'Parking', 'Security', 'Jogging Track', 'Children Play Area'],
        images: [
            'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop'
        ],
        yearBuilt: 2023,
        verificationStatus: 'verified',
        isFeatured: true,
        status: 'active',
        owner: { id: 'user_009', name: 'Karthik Reddy', phone: '+919900112233', email: 'karthik.reddy@gmail.com', isVerified: true },
        viewCount: 723, contactCount: 48,
        createdAt: new Date('2026-02-12').toISOString()
    },
    {
        id: 'prop_017',
        title: '2 BHK for Rent in Koramangala — Tech Hub',
        description: 'Prime location 2 BHK in Koramangala 4th Block, the startup capital of India. Walking distance to cafes, co-working spaces, and Forum Mall. Fully furnished with modern interiors.',
        propertyType: 'flat',
        listingType: 'rent',
        bhk: '2 BHK',
        bathrooms: 2,
        sqft: 1100,
        furnishing: 'fully-furnished',
        price: 40000,
        latitude: 12.9352,
        longitude: 77.6245,
        address: '4th Block, Koramangala, Bangalore',
        city: 'Bangalore',
        area: 'Koramangala',
        pincode: '560034',
        amenities: ['Parking', 'Security', 'Power Backup', 'AC', 'WiFi', 'Gym'],
        images: [
            'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=600&fit=crop'
        ],
        yearBuilt: 2020,
        verificationStatus: 'verified',
        isFeatured: false,
        status: 'active',
        owner: { id: 'user_009', name: 'Karthik Reddy', phone: '+919900112233', email: 'karthik.reddy@gmail.com', isVerified: true },
        viewCount: 534, contactCount: 67,
        createdAt: new Date('2026-02-13').toISOString()
    },
    {
        id: 'prop_018',
        title: '4 BHK Villa in Sarjapur Road',
        description: 'Stunning 4 BHK independent villa in a gated community on Sarjapur Road. Features rooftop terrace with BBQ area, private garden, home gym, and panoramic views of surrounding greenery.',
        propertyType: 'villa',
        listingType: 'sell',
        bhk: '4 BHK',
        bathrooms: 4,
        sqft: 3500,
        furnishing: 'fully-furnished',
        price: 32000000,
        latitude: 12.8660,
        longitude: 77.7850,
        address: 'Sarjapur Road, Bangalore',
        city: 'Bangalore',
        area: 'Sarjapur Road',
        pincode: '560035',
        amenities: ['Private Garden', 'Rooftop BBQ', 'Home Gym', 'Parking', 'Security', 'CCTV', 'Servant Quarter', 'Rainwater Harvesting'],
        images: [
            'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop'
        ],
        yearBuilt: 2024,
        verificationStatus: 'verified',
        isFeatured: true,
        status: 'active',
        owner: { id: 'user_010', name: 'Suresh Iyengar', phone: '+919845098765', email: 'suresh.iyengar@gmail.com', isVerified: true },
        viewCount: 456, contactCount: 29,
        createdAt: new Date('2026-02-14').toISOString()
    },
    // ==================== HYDERABAD ====================
    {
        id: 'prop_019',
        title: '3 BHK in My Home Bhooja — HITEC City',
        description: 'Premium 3 BHK in the award-winning My Home Bhooja with infinity pool, sky lounge, and direct access to HITEC City IT corridor. Italian marble, VRV AC, and smart home features included.',
        propertyType: 'flat',
        listingType: 'sell',
        bhk: '3 BHK',
        bathrooms: 3,
        sqft: 2100,
        furnishing: 'fully-furnished',
        price: 22000000,
        latitude: 17.4435,
        longitude: 78.3772,
        address: 'My Home Bhooja, HITEC City, Hyderabad',
        city: 'Hyderabad',
        area: 'HITEC City',
        pincode: '500081',
        amenities: ['Infinity Pool', 'Sky Lounge', 'Gym', 'Smart Home', 'VRV AC', 'Parking', 'Security', 'Club House', 'Intercom'],
        images: [
            'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop'
        ],
        yearBuilt: 2024,
        verificationStatus: 'verified',
        isFeatured: true,
        status: 'active',
        owner: { id: 'user_011', name: 'Ravi Teja Reddy', phone: '+919848012345', email: 'ravi.teja@gmail.com', isVerified: true },
        viewCount: 612, contactCount: 44,
        createdAt: new Date('2026-02-15').toISOString()
    },
    {
        id: 'prop_020',
        title: '2 BHK for Rent in Gachibowli',
        description: 'Spacious 2 BHK near Financial District and Google/Microsoft offices. Gated community with excellent amenities. Close to ISB, IIIT, and University of Hyderabad.',
        propertyType: 'flat',
        listingType: 'rent',
        bhk: '2 BHK',
        bathrooms: 2,
        sqft: 1250,
        furnishing: 'semi-furnished',
        price: 28000,
        latitude: 17.4401,
        longitude: 78.3489,
        address: 'Financial District, Gachibowli, Hyderabad',
        city: 'Hyderabad',
        area: 'Gachibowli',
        pincode: '500032',
        amenities: ['Parking', 'Lift', 'Security', 'Swimming Pool', 'Gym', 'Power Backup', 'Children Play Area'],
        images: [
            'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop'
        ],
        yearBuilt: 2022,
        verificationStatus: 'verified',
        isFeatured: false,
        status: 'active',
        owner: { id: 'user_011', name: 'Ravi Teja Reddy', phone: '+919848012345', email: 'ravi.teja@gmail.com', isVerified: true },
        viewCount: 387, contactCount: 52,
        createdAt: new Date('2026-02-16').toISOString()
    },
    {
        id: 'prop_021',
        title: 'Residential Plot in Shamshabad — Near Airport',
        description: '200 sq.yard HMDA approved residential plot near Rajiv Gandhi International Airport. Ideal for investment with proposed metro connectivity. Clear title with all approvals in place.',
        propertyType: 'plot',
        listingType: 'sell',
        bhk: 'Plot',
        bathrooms: 0,
        sqft: 1800,
        furnishing: 'unfurnished',
        price: 5400000,
        latitude: 17.2403,
        longitude: 78.4294,
        address: 'Near RGIA Airport, Shamshabad, Hyderabad',
        city: 'Hyderabad',
        area: 'Shamshabad',
        pincode: '501218',
        amenities: ['Gated Community', 'Underground Drainage', 'Wide Roads', 'Park', 'HMDA Approved'],
        images: [
            'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1628624747186-a941c476b7ef?w=800&h=600&fit=crop'
        ],
        yearBuilt: 2025,
        verificationStatus: 'verified',
        isFeatured: false,
        status: 'active',
        owner: { id: 'user_012', name: 'Srinivas Rao', phone: '+919866054321', email: 'srinivas.rao@gmail.com', isVerified: true },
        viewCount: 234, contactCount: 19,
        createdAt: new Date('2026-02-17').toISOString()
    },
    // ==================== PUNE ====================
    {
        id: 'prop_022',
        title: '3 BHK in Lodha Belmondo — Pune',
        description: 'Resort-style living in Lodha Belmondo on the banks of Pavana River. 3 BHK with private balcony overlooking the river. Features 50+ amenities including water sports, golf, equestrian club, and organic farm.',
        propertyType: 'flat',
        listingType: 'sell',
        bhk: '3 BHK',
        bathrooms: 3,
        sqft: 1750,
        furnishing: 'semi-furnished',
        price: 16500000,
        latitude: 18.7167,
        longitude: 73.4833,
        address: 'Lodha Belmondo, Gahunje, Pune',
        city: 'Pune',
        area: 'Gahunje',
        pincode: '412108',
        amenities: ['River View', 'Golf Course', 'Swimming Pool', 'Equestrian Club', 'Organic Farm', 'Water Sports', 'Gym', 'Club House', 'Parking'],
        images: [
            'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&h=600&fit=crop'
        ],
        yearBuilt: 2023,
        verificationStatus: 'verified',
        isFeatured: true,
        status: 'active',
        owner: { id: 'user_013', name: 'Aditya Joshi', phone: '+919850567890', email: 'aditya.joshi@gmail.com', isVerified: true },
        viewCount: 502, contactCount: 33,
        createdAt: new Date('2026-02-18').toISOString()
    },
    {
        id: 'prop_023',
        title: '2 BHK for Rent in Hinjewadi Phase 1',
        description: 'Well-connected 2 BHK near Hinjewadi IT Park. 5 minutes from Infosys, TCS, and Wipro campuses. Furnished with queen bed, study table, sofa, and fully equipped kitchen.',
        propertyType: 'flat',
        listingType: 'rent',
        bhk: '2 BHK',
        bathrooms: 2,
        sqft: 950,
        furnishing: 'fully-furnished',
        price: 22000,
        latitude: 18.5913,
        longitude: 73.7389,
        address: 'Phase 1, Hinjewadi, Pune',
        city: 'Pune',
        area: 'Hinjewadi',
        pincode: '411057',
        amenities: ['Parking', 'Lift', 'Security', 'AC', 'Power Backup', 'Gym', 'Children Play Area'],
        images: [
            'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&h=600&fit=crop'
        ],
        yearBuilt: 2021,
        verificationStatus: 'verified',
        isFeatured: false,
        status: 'active',
        owner: { id: 'user_013', name: 'Aditya Joshi', phone: '+919850567890', email: 'aditya.joshi@gmail.com', isVerified: true },
        viewCount: 445, contactCount: 58,
        createdAt: new Date('2026-02-19').toISOString()
    },
    {
        id: 'prop_024',
        title: 'Commercial Office Space in Baner',
        description: '1200 sqft fully furnished office space in Baner IT hub. Plug-and-play with 15 workstations, conference room, pantry, and high-speed internet. Suitable for startups and small companies.',
        propertyType: 'commercial',
        listingType: 'rent',
        bhk: 'Office',
        bathrooms: 2,
        sqft: 1200,
        furnishing: 'fully-furnished',
        price: 55000,
        latitude: 18.5590,
        longitude: 73.7868,
        address: 'Baner Road, Near Orchid School, Pune',
        city: 'Pune',
        area: 'Baner',
        pincode: '411045',
        amenities: ['15 Workstations', 'Conference Room', 'Pantry', 'High-Speed Internet', 'Parking', 'Security', 'Power Backup', 'Lift'],
        images: [
            'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop'
        ],
        yearBuilt: 2022,
        verificationStatus: 'verified',
        isFeatured: false,
        status: 'active',
        owner: { id: 'user_014', name: 'Manish Patil', phone: '+919823456780', email: 'manish.patil@gmail.com', isVerified: true },
        viewCount: 312, contactCount: 26,
        createdAt: new Date('2026-02-20').toISOString()
    },
    // ==================== MORE LUCKNOW ====================
    {
        id: 'prop_025',
        title: '1 BHK for Rent — Budget Friendly in Chinhat',
        description: 'Clean and affordable 1 BHK near Chinhat Industrial Area. Ground floor with separate entry, small garden patch, and ample parking. Best for students and bachelors.',
        propertyType: 'flat',
        listingType: 'rent',
        bhk: '1 BHK',
        bathrooms: 1,
        sqft: 500,
        furnishing: 'unfurnished',
        price: 8000,
        latitude: 26.8700,
        longitude: 81.0200,
        address: 'Near Chinhat Crossing, Lucknow',
        city: 'Lucknow',
        area: 'Chinhat',
        pincode: '226028',
        amenities: ['Parking', 'Water Supply 24x7'],
        images: [
            'https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800&h=600&fit=crop'
        ],
        yearBuilt: 2015,
        verificationStatus: 'verified',
        isFeatured: false,
        status: 'active',
        owner: { id: 'user_003', name: 'Sanjay Gupta', phone: '+919988776655', email: 'sanjay.gupta@gmail.com', isVerified: true },
        viewCount: 145, contactCount: 22,
        createdAt: new Date('2026-02-21').toISOString()
    },
    {
        id: 'prop_026',
        title: 'Residential Plot in Shaheed Path',
        description: '1000 sqft RERA registered residential plot on Shaheed Path, one of the fastest developing corridors of Lucknow. Near proposed Metro station and IT City. Excellent appreciation potential.',
        propertyType: 'plot',
        listingType: 'sell',
        bhk: 'Plot',
        bathrooms: 0,
        sqft: 1000,
        furnishing: 'unfurnished',
        price: 3500000,
        latitude: 26.8100,
        longitude: 81.0100,
        address: 'Shaheed Path, Near IT City, Lucknow',
        city: 'Lucknow',
        area: 'Shaheed Path',
        pincode: '226013',
        amenities: ['Boundary Wall', 'Wide Road', 'Park Nearby', 'RERA Registered'],
        images: [
            'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&h=600&fit=crop'
        ],
        yearBuilt: 2025,
        verificationStatus: 'verified',
        isFeatured: false,
        status: 'active',
        owner: { id: 'user_004', name: 'Amit Agarwal', phone: '+919876501234', email: 'amit.agarwal@gmail.com', isVerified: true },
        viewCount: 278, contactCount: 20,
        createdAt: new Date('2026-02-22').toISOString()
    },
    {
        id: 'prop_027',
        title: '4 BHK Duplex in Vrindavan Yojna',
        description: 'Magnificent duplex apartment with double-height living room, spiral staircase, terrace garden, and panoramic city views. Located in the upscale Vrindavan Yojna sector with excellent social infrastructure.',
        propertyType: 'flat',
        listingType: 'sell',
        bhk: '4 BHK',
        bathrooms: 3,
        sqft: 2800,
        furnishing: 'semi-furnished',
        price: 18500000,
        latitude: 26.7800,
        longitude: 81.0000,
        address: 'Sector 8, Vrindavan Yojna, Lucknow',
        city: 'Lucknow',
        area: 'Vrindavan Yojna',
        pincode: '226029',
        amenities: ['Parking', 'Lift', 'Security', 'Swimming Pool', 'Gym', 'Terrace Garden', 'Club House', 'Children Play Area'],
        images: [
            'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop'
        ],
        yearBuilt: 2023,
        verificationStatus: 'verified',
        isFeatured: true,
        status: 'active',
        owner: { id: 'user_001', name: 'Rajesh Kumar Verma', phone: '+919876543210', email: 'rajesh.verma@gmail.com', isVerified: true },
        viewCount: 398, contactCount: 27,
        createdAt: new Date('2026-02-23').toISOString()
    },
    // ==================== DELHI ====================
    {
        id: 'prop_028',
        title: '3 BHK Builder Floor in Vasant Kunj',
        description: 'Newly constructed 3 BHK builder floor in Vasant Kunj C-Block with wooden flooring, modular kitchen, and large balcony. Close to DLF Promenade, Vasant Kunj Mall, and international schools.',
        propertyType: 'house',
        listingType: 'sell',
        bhk: '3 BHK',
        bathrooms: 3,
        sqft: 1800,
        furnishing: 'semi-furnished',
        price: 28000000,
        latitude: 28.5189,
        longitude: 77.1570,
        address: 'C-Block, Vasant Kunj, New Delhi',
        city: 'Delhi',
        area: 'Vasant Kunj',
        pincode: '110070',
        amenities: ['Parking', 'Modular Kitchen', 'Wooden Flooring', 'Power Backup', 'Security'],
        images: [
            'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&h=600&fit=crop'
        ],
        yearBuilt: 2024,
        verificationStatus: 'verified',
        isFeatured: true,
        status: 'active',
        owner: { id: 'user_015', name: 'Rohit Kapoor', phone: '+919810678901', email: 'rohit.kapoor@gmail.com', isVerified: true },
        viewCount: 567, contactCount: 39,
        createdAt: new Date('2026-02-24').toISOString()
    },
    {
        id: 'prop_029',
        title: '2 BHK for Rent in Saket — Near Metro',
        description: 'Bright and airy 2 BHK just 3 minutes from Saket Metro Station. Overlooking the lush Sai Baba temple gardens. Close to Select Citywalk Mall, Max Hospital, and DLF Place.',
        propertyType: 'flat',
        listingType: 'rent',
        bhk: '2 BHK',
        bathrooms: 2,
        sqft: 1000,
        furnishing: 'fully-furnished',
        price: 45000,
        latitude: 28.5244,
        longitude: 77.2167,
        address: 'Near Saket Metro, Saket, New Delhi',
        city: 'Delhi',
        area: 'Saket',
        pincode: '110017',
        amenities: ['Metro Nearby', 'Parking', 'Security', 'AC', 'WiFi', 'Power Backup', 'Lift'],
        images: [
            'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=800&h=600&fit=crop'
        ],
        yearBuilt: 2019,
        verificationStatus: 'verified',
        isFeatured: false,
        status: 'active',
        owner: { id: 'user_015', name: 'Rohit Kapoor', phone: '+919810678901', email: 'rohit.kapoor@gmail.com', isVerified: true },
        viewCount: 423, contactCount: 55,
        createdAt: new Date('2026-02-25').toISOString()
    },
    {
        id: 'prop_030',
        title: 'Commercial Showroom in Connaught Place',
        description: 'Prime commercial showroom in the heart of Connaught Place, Block B. Ground floor with massive frontage, ideal for flagship retail stores, restaurants, or luxury brand outlets. Footfall of 10000+ daily.',
        propertyType: 'commercial',
        listingType: 'rent',
        bhk: 'Showroom',
        bathrooms: 2,
        sqft: 2000,
        furnishing: 'unfurnished',
        price: 350000,
        latitude: 28.6328,
        longitude: 77.2197,
        address: 'Block B, Connaught Place, New Delhi',
        city: 'Delhi',
        area: 'Connaught Place',
        pincode: '110001',
        amenities: ['Ground Floor', 'Front Facing', 'Parking', 'Power Backup', 'Fire Safety', 'CCTV'],
        images: [
            'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop'
        ],
        yearBuilt: 2010,
        verificationStatus: 'verified',
        isFeatured: true,
        status: 'active',
        owner: { id: 'user_006', name: 'Neeraj Malhotra', phone: '+919871009876', email: 'neeraj.malhotra@gmail.com', isVerified: true },
        viewCount: 890, contactCount: 45,
        createdAt: new Date('2026-02-26').toISOString()
    }
];

// Export for Node.js (API server)
if (typeof module !== 'undefined' && module.exports) {
    module.exports = REAL_LISTINGS;
}

// Export for browser (static fallback)
if (typeof window !== 'undefined') {
    window.REAL_LISTINGS = REAL_LISTINGS;
}
